### ISSUE TITLE
Website categories

### ISSUE THREAD

**Issue by karlolukic** [ghostery/whotracks.me#210]
Hi guys, after working extensively with Global and EU/US `sites.csv` datasets, I noticed wrongly categorized websites. This could be valuable to someone working with panel data from 2017 onward where website categories are important. I note problematic websites and proposed recoded categories below for both datasets.

# Global sites' categories

- `nih.gov` - categorized as Reference site until September 2018 release when it was properly categorized as Government; should be Government from the start.
- `targobank.de` - categorized as Business site; should be Banking site.
- `ddl-warez.to` - categorized as Recreation site; should be Entertainment site.

# EU/US sites' categories

- `ca.gov` - categorized as Reference site until September 2018 release when it was properly categorized as Government; should be Government from the start.
- `europa.eu` - same as above.
- `nasa.gov` - same as above.
- `nih.gov` - same as above.
- `state.gov` - same as above.
- `gov.uk` - same as above.
- `irs.gov` - categorized as Business site until September 2018 release when it was properly categorized as Government; should be Government from the start.
- `tax.service.gov.uk` - same as above.
- `weather.gov` - categorized as News and Portals site until September 2018 release when it was properly categorized as Government; should be Government from the start.
- `targobank.de` - categorized as Business site; should be Banking site.
- `audible.com` categorized as Entertainment; should be E-commerce.
- `discover.com` categorized as News and Portals; should be Banking site.
- `ddl-warez.to` - categorized as Recreation site; should be Entertainment site.
- `yelp.de` categorized as Entertainment; should be Reference.
-  `stylight.de` categorized as Reference; should be E-commerce.
- `linguee.de` categorized as News and Portals; should be Reference.

**Comment by sammacbeth** [comment]
Thanks for this. I'll get these categories updated for next month. We could also publish the list of site to category mappings in this repo to allow external contributors to update them.

**Comment by karlolukic** [comment]
> Thanks for this. I'll get these categories updated for next month. 

No problem. Awesome!

> We could also publish the list of site to category mappings in this repo to allow external contributors to update them.

That's a great idea Sam. How can we proceed with this?

> If the categories are eventually correct, do we need to update the older `sites.csv` files to fix them? It should be easy to use the most recent mappings in any analysis.

Agree, the most recent mapping option is less effort. The users of `sites.csv` datsets, however, should be aware about this. We could note somewhere: "please use the latest site-to-category mapping for older datasets" or similar. What do you think?

> On the older hand, a change in site category over time could represent a change in purpose of a site.

True. We could use Internet Archive to double-check above—and any additional—websites if their categories are constant over time. I would assume that, in most cases, websites do not change their categories over time. What do you think?
