### ISSUE TITLE
Update .sql data

### ISSUE THREAD

**Issue by rosstex** [ghostery/whotracks.me#227]
How come the SQL database is still from July 2020 data when the repo has data up to Dec 2020?

**Comment by philipp-classen** [comment]
The changes in the SQL database reflect manual updates, while the other data is generated. The generated data will change every month, but for the SQL data it can happen that nothing changes over multiple months.

But I saw that we had changes recently, which will be included in https://github.com/ghostery/whotracks.me/pull/228

Thanks for pointing out.
