### ISSUE TITLE
Library version conflicts when installing from source

### ISSUE THREAD

**Issue by ducalpha** [ghostery/whotracks.me#245]
I tried to install whotracks.me from source but there were library version conflicts
How to reproduce:

```
 $  git clone https://github.com/ghostery/whotracks.me.git
 $  cd whotracks.me
 $  conda create -n whotracksme python=3.8
 $  conda activate whotracksme
 $  pip install -r requirements.txt
...
ERROR: Cannot install -r requirements.txt (line 9) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1
```

My system: Ubuntu 18.04.

A quick fix: update the version of `requests` in `requirements.txt`:
```
--- a/requirements.txt
+++ b/requirements.txt
@@ -6,6 +6,6 @@ numpy==1.19.1
 pandas==1.1.2
 python-dateutil==2.8.1
 pytz==2020.1
-requests==2.24.0
+requests==2.25.1
 six==1.15.0
 urllib3==1.26.5
```

**Comment by y3ti** [comment]
@ducalpha thank you for catching this. I created a new pull request that fixes this issue - https://github.com/ghostery/whotracks.me/pull/246

I bumped `requests` in #241, but I forgot to update `requests.txt`. I added installing Python packages from `requests.txt` to our GitHub Actions Workflow. Before, we tested only package installation from `requirements-dev.txt`
